# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1500, 876)
        MainWindow.setStatusTip("")
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.screensWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.screensWidget.setGeometry(QtCore.QRect(0, 0, 1491, 851))
        self.screensWidget.setObjectName("screensWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget_7 = QtWidgets.QWidget(self.page)
        self.widget_7.setGeometry(QtCore.QRect(0, 340, 1491, 131))
        self.widget_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_7.setObjectName("widget_7")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 1491, 61))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font-family: \"inter\"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.current_loading_model = QtWidgets.QLabel(self.widget_7)
        self.current_loading_model.setGeometry(QtCore.QRect(0, 60, 1491, 61))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(12)
        self.current_loading_model.setFont(font)
        self.current_loading_model.setStyleSheet("font-family: \"inter\"")
        self.current_loading_model.setAlignment(QtCore.Qt.AlignCenter)
        self.current_loading_model.setObjectName("current_loading_model")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 760, 1481, 111))
        self.label_2.setStyleSheet("background-image: url(:/background-image/generium_logo.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../.designer/backup/app/icons/generium_logo.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.screensWidget.addWidget(self.page)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.widget_3 = QtWidgets.QWidget(self.page_1)
        self.widget_3.setGeometry(QtCore.QRect(10, 433, 391, 421))
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(0, 250, 391, 171))
        self.widget_4.setObjectName("widget_4")
        self.westernBlotImageName = QtWidgets.QLabel(self.widget_4)
        self.westernBlotImageName.setEnabled(True)
        self.westernBlotImageName.setGeometry(QtCore.QRect(5, 130, 381, 31))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        self.westernBlotImageName.setFont(font)
        self.westernBlotImageName.setStyleSheet("QLabel {\n"
"        font-family: \"inter\";\n"
"\n"
"}")
        self.westernBlotImageName.setAlignment(QtCore.Qt.AlignCenter)
        self.westernBlotImageName.setWordWrap(True)
        self.westernBlotImageName.setObjectName("westernBlotImageName")
        self.openOutputWesternBlotButton = QtWidgets.QPushButton(self.widget_4)
        self.openOutputWesternBlotButton.setEnabled(False)
        self.openOutputWesternBlotButton.setGeometry(QtCore.QRect(20, 50, 170, 50))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        self.openOutputWesternBlotButton.setFont(font)
        self.openOutputWesternBlotButton.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #7576D6;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #a1a2d8;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  #8e8fd7;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  #58599e;\n"
"}\n"
"")
        self.openOutputWesternBlotButton.setObjectName("openOutputWesternBlotButton")
        self.loadWesternBlotImageButton = QtWidgets.QPushButton(self.widget_4)
        self.loadWesternBlotImageButton.setEnabled(True)
        self.loadWesternBlotImageButton.setGeometry(QtCore.QRect(200, 50, 171, 51))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        self.loadWesternBlotImageButton.setFont(font)
        self.loadWesternBlotImageButton.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #7576D6;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #a1a2d8;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  #8e8fd7;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  #58599e;\n"
"}\n"
"")
        self.loadWesternBlotImageButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.loadWesternBlotImageButton.setText("Загрузить\n"
"Изображение")
        self.loadWesternBlotImageButton.setObjectName("loadWesternBlotImageButton")
        self.westernBlotImage = QtWidgets.QLabel(self.widget_3)
        self.westernBlotImage.setGeometry(QtCore.QRect(20, 50, 350, 230))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(8)
        self.westernBlotImage.setFont(font)
        self.westernBlotImage.setStyleSheet("\n"
"QLabel {\n"
"        font-family: \"inter\";\n"
"        border: 1px solid gray;\n"
"}")
        self.westernBlotImage.setAlignment(QtCore.Qt.AlignCenter)
        self.westernBlotImage.setObjectName("westernBlotImage")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(70, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("QLabel {\n"
"        font-family: \"inter\";\n"
"\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.widget_2 = QtWidgets.QWidget(self.page_1)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 391, 401))
        self.widget_2.setObjectName("widget_2")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(0, 240, 391, 161))
        self.widget_5.setObjectName("widget_5")
        self.openOutputElectrophoresisButton = QtWidgets.QPushButton(self.widget_5)
        self.openOutputElectrophoresisButton.setEnabled(False)
        self.openOutputElectrophoresisButton.setGeometry(QtCore.QRect(20, 50, 170, 50))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        self.openOutputElectrophoresisButton.setFont(font)
        self.openOutputElectrophoresisButton.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #7576D6;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #a1a2d8;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  #8e8fd7;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  #58599e;\n"
"}\n"
"")
        self.openOutputElectrophoresisButton.setObjectName("openOutputElectrophoresisButton")
        self.electrophoresisImageName = QtWidgets.QLabel(self.widget_5)
        self.electrophoresisImageName.setGeometry(QtCore.QRect(5, 120, 381, 31))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        self.electrophoresisImageName.setFont(font)
        self.electrophoresisImageName.setStyleSheet("QLabel {\n"
"        font-family: \"inter\";\n"
"}")
        self.electrophoresisImageName.setAlignment(QtCore.Qt.AlignCenter)
        self.electrophoresisImageName.setWordWrap(True)
        self.electrophoresisImageName.setObjectName("electrophoresisImageName")
        self.loadElectrophoresisImageButton = QtWidgets.QPushButton(self.widget_5)
        self.loadElectrophoresisImageButton.setGeometry(QtCore.QRect(200, 50, 170, 50))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        self.loadElectrophoresisImageButton.setFont(font)
        self.loadElectrophoresisImageButton.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #7576D6;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #a1a2d8;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  #8e8fd7;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  #58599e;\n"
"}\n"
"")
        self.loadElectrophoresisImageButton.setObjectName("loadElectrophoresisImageButton")
        self.electrophoresisImage = QtWidgets.QLabel(self.widget_2)
        self.electrophoresisImage.setGeometry(QtCore.QRect(20, 40, 350, 230))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(8)
        self.electrophoresisImage.setFont(font)
        self.electrophoresisImage.setStyleSheet("\n"
"QLabel {\n"
"        font-family: \"inter\";\n"
"        border: 1px solid gray;\n"
"}")
        self.electrophoresisImage.setAlignment(QtCore.Qt.AlignCenter)
        self.electrophoresisImage.setObjectName("electrophoresisImage")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(70, 0, 251, 31))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("QLabel {\n"
"        font-family: \"inter\";\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.widget = QtWidgets.QWidget(self.page_1)
        self.widget.setGeometry(QtCore.QRect(429, 10, 661, 841))
        self.widget.setObjectName("widget")
        self.visualisationImage = QtWidgets.QLabel(self.widget)
        self.visualisationImage.setGeometry(QtCore.QRect(10, 0, 641, 461))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(9)
        self.visualisationImage.setFont(font)
        self.visualisationImage.setStyleSheet("\n"
"QLabel {\n"
"        font-family: \"inter\";\n"
"        border: 1px solid gray;\n"
"}")
        self.visualisationImage.setAlignment(QtCore.Qt.AlignCenter)
        self.visualisationImage.setObjectName("visualisationImage")
        self.visualisationImageControlls = QtWidgets.QWidget(self.widget)
        self.visualisationImageControlls.setEnabled(False)
        self.visualisationImageControlls.setGeometry(QtCore.QRect(10, 470, 641, 371))
        self.visualisationImageControlls.setObjectName("visualisationImageControlls")
        self.startLoadingButton = QtWidgets.QPushButton(self.visualisationImageControlls)
        self.startLoadingButton.setEnabled(False)
        self.startLoadingButton.setGeometry(QtCore.QRect(0, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(11)
        self.startLoadingButton.setFont(font)
        self.startLoadingButton.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #7576D6;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #a1a2d8;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  #8e8fd7;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  #58599e;\n"
"}\n"
"")
        self.startLoadingButton.setObjectName("startLoadingButton")
        self.marginHorizontalSliderValue = QtWidgets.QSpinBox(self.visualisationImageControlls)
        self.marginHorizontalSliderValue.setGeometry(QtCore.QRect(600, 330, 42, 22))
        self.marginHorizontalSliderValue.setMinimum(-50)
        self.marginHorizontalSliderValue.setMaximum(50)
        self.marginHorizontalSliderValue.setDisplayIntegerBase(10)
        self.marginHorizontalSliderValue.setObjectName("marginHorizontalSliderValue")
        self.marginVerticalSlider = QtWidgets.QSlider(self.visualisationImageControlls)
        self.marginVerticalSlider.setGeometry(QtCore.QRect(0, 330, 591, 22))
        self.marginVerticalSlider.setStyleSheet("")
        self.marginVerticalSlider.setMinimum(-50)
        self.marginVerticalSlider.setMaximum(50)
        self.marginVerticalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.marginVerticalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.marginVerticalSlider.setTickInterval(3)
        self.marginVerticalSlider.setObjectName("marginVerticalSlider")
        self.openOutputImageButton = QtWidgets.QPushButton(self.visualisationImageControlls)
        self.openOutputImageButton.setEnabled(False)
        self.openOutputImageButton.setGeometry(QtCore.QRect(400, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(11)
        self.openOutputImageButton.setFont(font)
        self.openOutputImageButton.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #7576D6;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #a1a2d8;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  #8e8fd7;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  #58599e;\n"
"}\n"
"")
        self.openOutputImageButton.setObjectName("openOutputImageButton")
        self.marginHorizontalSlider = QtWidgets.QSlider(self.visualisationImageControlls)
        self.marginHorizontalSlider.setGeometry(QtCore.QRect(0, 240, 591, 22))
        self.marginHorizontalSlider.setStyleSheet("")
        self.marginHorizontalSlider.setMinimum(-50)
        self.marginHorizontalSlider.setMaximum(50)
        self.marginHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.marginHorizontalSlider.setInvertedAppearance(False)
        self.marginHorizontalSlider.setInvertedControls(False)
        self.marginHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.marginHorizontalSlider.setTickInterval(3)
        self.marginHorizontalSlider.setObjectName("marginHorizontalSlider")
        self.marginVerticalSliderValue = QtWidgets.QSpinBox(self.visualisationImageControlls)
        self.marginVerticalSliderValue.setGeometry(QtCore.QRect(600, 240, 42, 22))
        self.marginVerticalSliderValue.setMinimum(-50)
        self.marginVerticalSliderValue.setMaximum(50)
        self.marginVerticalSliderValue.setObjectName("marginVerticalSliderValue")
        self.label = QtWidgets.QLabel(self.visualisationImageControlls)
        self.label.setGeometry(QtCore.QRect(0, 130, 641, 31))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font-family: \"inter\";\n"
"color: black;\n"
"font-weight: \"normal\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.analyzeStatus = QtWidgets.QLabel(self.visualisationImageControlls)
        self.analyzeStatus.setGeometry(QtCore.QRect(0, 80, 641, 31))
        self.analyzeStatus.setText("")
        self.analyzeStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.analyzeStatus.setWordWrap(True)
        self.analyzeStatus.setObjectName("analyzeStatus")
        self.label_4 = QtWidgets.QLabel(self.visualisationImageControlls)
        self.label_4.setGeometry(QtCore.QRect(230, 200, 191, 21))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font-family: \"inter\";\n"
"color: black;\n"
"font-weight: \"normal\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.visualisationImageControlls)
        self.label_8.setGeometry(QtCore.QRect(230, 290, 191, 21))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font-family: \"inter\";\n"
"color: black;\n"
"font-weight: \"normal\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.widget_6 = QtWidgets.QWidget(self.page_1)
        self.widget_6.setGeometry(QtCore.QRect(1120, 10, 371, 841))
        self.widget_6.setObjectName("widget_6")
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 371, 31))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("QLabel {\n"
"        font-family: \"inter\";\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.saveDataButton = QtWidgets.QPushButton(self.widget_6)
        self.saveDataButton.setEnabled(False)
        self.saveDataButton.setGeometry(QtCore.QRect(40, 770, 301, 51))
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(11)
        self.saveDataButton.setFont(font)
        self.saveDataButton.setStyleSheet("QPushButton:enabled {\n"
"    background-color: #7576D6;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #a1a2d8;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-family: \"inter\";\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  #8e8fd7;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  #58599e;\n"
"}\n"
"")
        self.saveDataButton.setObjectName("saveDataButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_6)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 60, 371, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        self.info_3.setFont(font)
        self.info_3.setStyleSheet("QLabel {\n"
"        font-family: \"inter\";\n"
"}")
        self.info_3.setScaledContents(False)
        self.info_3.setWordWrap(True)
        self.info_3.setOpenExternalLinks(False)
        self.info_3.setObjectName("info_3")
        self.verticalLayout.addWidget(self.info_3)
        self.info_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        self.info_4.setFont(font)
        self.info_4.setStyleSheet("QLabel {\n"
"        font-family: \"inter\";\n"
"}")
        self.info_4.setScaledContents(False)
        self.info_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.info_4.setWordWrap(True)
        self.info_4.setOpenExternalLinks(False)
        self.info_4.setObjectName("info_4")
        self.verticalLayout.addWidget(self.info_4)
        self.info_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        self.info_2.setFont(font)
        self.info_2.setStyleSheet("QLabel {\n"
"        font-family: \"inter\";\n"
"}")
        self.info_2.setScaledContents(False)
        self.info_2.setWordWrap(True)
        self.info_2.setOpenExternalLinks(False)
        self.info_2.setObjectName("info_2")
        self.verticalLayout.addWidget(self.info_2)
        self.info_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("inter")
        font.setPointSize(10)
        self.info_1.setFont(font)
        self.info_1.setStyleSheet("QLabel {\n"
"        font-family: \"inter\";\n"
"}")
        self.info_1.setObjectName("info_1")
        self.verticalLayout.addWidget(self.info_1)
        self.line = QtWidgets.QFrame(self.page_1)
        self.line.setGeometry(QtCore.QRect(400, 10, 31, 841))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.page_1)
        self.line_2.setGeometry(QtCore.QRect(1090, 10, 31, 841))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.page_1)
        self.line_3.setGeometry(QtCore.QRect(10, 410, 391, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.screensWidget.addWidget(self.page_1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.screensWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Анализатор опытов электрофореза и вестерн-блота"))
        self.label_5.setText(_translate("MainWindow", "Выполняется загрузка моделей. Подождите..."))
        self.current_loading_model.setText(_translate("MainWindow", "Пусто"))
        self.westernBlotImageName.setText(_translate("MainWindow", "Снимок не загружен"))
        self.openOutputWesternBlotButton.setText(_translate("MainWindow", "Открыть\n"
"Полностью"))
        self.westernBlotImage.setText(_translate("MainWindow", "Не загружено"))
        self.label_6.setText(_translate("MainWindow", "Вестерн-блот"))
        self.openOutputElectrophoresisButton.setText(_translate("MainWindow", "Открыть\n"
"Полностью"))
        self.electrophoresisImageName.setText(_translate("MainWindow", "Снимок не загружен"))
        self.loadElectrophoresisImageButton.setText(_translate("MainWindow", "Загрузить\n"
"Изображение"))
        self.electrophoresisImage.setText(_translate("MainWindow", "Не загружено"))
        self.label_7.setText(_translate("MainWindow", "Электрофорез"))
        self.visualisationImage.setText(_translate("MainWindow", "Не загружено"))
        self.startLoadingButton.setText(_translate("MainWindow", "Начать обработку"))
        self.openOutputImageButton.setText(_translate("MainWindow", "Открыть полностью"))
        self.label.setText(_translate("MainWindow", "Регулировка позиции"))
        self.label_4.setText(_translate("MainWindow", "Отступ по ширине:"))
        self.label_8.setText(_translate("MainWindow", "Отступ по высоте:"))
        self.label_3.setText(_translate("MainWindow", "Информация"))
        self.saveDataButton.setText(_translate("MainWindow", "Сохранить данные и снимок"))
        self.info_3.setText(_translate("MainWindow", "Распозннаные области на снимках вестерн-блота: нет"))
        self.info_4.setText(_translate("MainWindow", "Отношения количество белков вестерн-блота к электрофореза: нет"))
        self.info_2.setText(_translate("MainWindow", "Распозннаные области на снимках электрофореза: нет"))
        self.info_1.setText(_translate("MainWindow", "Распознанные области: нет"))
import images_rc
